name: first
description: "Aplikasi mantab."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"
dependencies:
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.5
  firebase_core: ^2.29.0
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  rename: ^3.0.2
  # youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/images/logo.png"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/images/
